# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d023c5474a662edbb1ed5a988c7a8a43f5f038f473f180f3406c63070926b8c18135aad68c57addd46bc8caeecaf6f767bd969d69b405a01de056c0a1f009d41

test:
  secret_key_base: f9aba091c7b4f1ab1a6e5ccccd0f3623bc2d8769cb3dbd9cbd8d35d2fa09c4ae50dfc497220cc3d3661adcda0f9881651460212ff8bcd8e080f7d237bad3fd35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
